### ISSUE TITLE
Rename app?

### ISSUE THREAD

**Issue by imagitama** [imagitama/chordmaster#11]
> Chord Master is the brand-name for a type of automated chording device produced for the ukulele. Competing products were sold under labels such as Noteless ...

We are competing with another popular product so we will never show up on the first page of search results unless we try really hard. Maybe it is worthwhile to rename the app now in the early stages? I can put a redirect from the old URL to the new one.

Possible names:

- ChordHelper

Please help me out by suggesting new names. It should be relatively short, indicate the purpose of the app and not be taken (domain wise and in search results).

**Comment by trybick** [comment]
- All Chords
- Muse Chord
- Chord Theory
- Six Chords

**Comment by imagitama** [comment]
Renamed to `https://chord.guide` 😎
