### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by trybick** [imagitama/chordmaster#12]
I'm guessing you already got alerts, but I can't seem to get to https://chord.guide or https://www.chordmaster.info/

**Comment by imagitama** [comment]
Thanks for the report. I will investigate ASAP. In the meantime you can skip to the Netlify domain: https://chordmaster.netlify.com/

**Comment by imagitama** [comment]
Closing as site is available at https://chord.guide/

**Comment by trybick** [comment]
@imagitama Hey there - the `.info` domain is still listed on your main github page title just FYI

**Comment by imagitama** [comment]
@trybick Updated
