### ISSUE TITLE
Add missing chords for all keys

### ISSUE THREAD

**Issue by imagitama** [imagitama/chordmaster#2]
There are numerous chords that are missing from the app. I have only added common ones (A, G, Em, etc.) and some intermediate ones (G#, Fm, Abm, etc.) but more advanced or less common ones are missing (the dominant 7th and suspended chords in particular).

We should at least add in the chords for all available keys so that there are no missing chords. As for other chords (like dom 7th and chords over other chords) we can add them ad hoc when someone asks for it or if you feel like contributing.

**Comment by trybick** [comment]
Will add the missing chords from `Abm` this weekend.

**Comment by imagitama** [comment]
> Will add the missing chords from Abm this weekend.

Sounds great! Thanks for your contribution.

**Comment by imagitama** [comment]
Since there are so many chords this issue will remain open for a long long time. I will change the goal of this issue to simply adding in all of the chords for all keys. Any other chords (like dom 7th) can be done ad hoc.
