### ISSUE TITLE
Add songs for all popular keys

### ISSUE THREAD

**Issue by imagitama** [imagitama/chordmaster#8]
I just added a "popular songs for each key" feature to help new guitar players learn some songs for different keys quickly. The aim is to have at least 1 song per popular/common key. Should be very well known pop/rock songs.

**Comment by trybick** [comment]
If a song is in Bb, but is usually played with a capo on 3 with a G chord, do you envision this is still an example of Bb?

**Comment by imagitama** [comment]
> If a song is in Bb, but is usually played with a capo on 3 with a G chord, do you envision this is still an example of Bb?

According to a quick search a capo changes the key of a song: https://music.stackexchange.com/questions/30933/on-a-guitar-what-keys-correspond-to-different-capo-positions

However for the first songs I intended to not have a capo. There are arguments for and against a capo but I think for now leave it off as it is simpler (but harder).
